$cat config/database.yml

development:
  adapter: postgresql
  database: simple_users_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: simple_users_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: simple_users_production
  pool: 5
  timeout: 5000
